# Generated by Django 5.0.1 on 2024-01-10 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='address',
            new_name='Exam_status',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='gender',
            new_name='date_of_birth',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='name',
            new_name='department',
        ),
        migrations.RemoveField(
            model_name='register',
            name='contact',
        ),
        migrations.AddField(
            model_name='register',
            name='experice',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='register',
            name='qualification',
            field=models.CharField(default='', max_length=50),
        ),
    ]
