# Generated by Django 5.0.1 on 2024-01-10 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0002_rename_address_register_exam_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='usertype',
            field=models.CharField(default='', max_length=50),
        ),
    ]
