# Generated by Django 5.0.1 on 2024-01-10 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0003_register_usertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='Stauts',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AlterField(
            model_name='register',
            name='Exam_status',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AlterField(
            model_name='register',
            name='usertype',
            field=models.IntegerField(null=True),
        ),
    ]
