# Generated by Django 5.0.1 on 2024-01-12 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0004_register_stauts_alter_register_exam_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Message', models.CharField(default='', max_length=50)),
                ('Date', models.CharField(default='', max_length=50)),
                ('Start_date', models.CharField(default='', max_length=50)),
                ('End_date', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
