# Generated by Django 5.0.1 on 2024-01-13 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0005_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='adress',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='register',
            name='contact',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
