# Generated by Django 5.0.1 on 2024-01-18 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0007_rename_experice_register_experience_register_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='adress',
            new_name='address',
        ),
        migrations.AddField(
            model_name='register',
            name='register_number',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='register',
            name='semester',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
