# Generated by Django 5.0.1 on 2024-01-27 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0009_departments_semesters'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subname', models.CharField(default='', max_length=50)),
                ('description', models.CharField(default='', max_length=500)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='public.departments')),
                ('semester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='public.semesters')),
            ],
        ),
    ]
