# Generated by Django 5.0.1 on 2024-01-27 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomname', models.CharField(default='', max_length=500)),
                ('row', models.IntegerField(null=True)),
                ('column', models.IntegerField(null=True)),
                ('strength', models.IntegerField(null=True)),
            ],
        ),
    ]
