# Generated by Django 5.0.1 on 2024-01-27 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam', '0001_initial'),
        ('public', '0010_subjects'),
    ]

    operations = [
        migrations.CreateModel(
            name='exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examname', models.CharField(default='', max_length=500)),
                ('date', models.DateField(default='', max_length=500)),
                ('starttime', models.TimeField(default='', max_length=500)),
                ('endtime', models.TimeField(default='', max_length=500)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='public.departments')),
                ('semester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='public.semesters')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='public.subjects')),
            ],
        ),
    ]
