# Generated by Django 5.0.1 on 2024-01-27 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Exam', '0002_exam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='department',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='subject',
        ),
    ]
