# Generated by Django 5.0.1 on 2024-01-27 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam', '0003_remove_exam_department_remove_exam_semester_and_more'),
        ('public', '0010_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='public.departments'),
        ),
        migrations.AddField(
            model_name='exam',
            name='semester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='public.semesters'),
        ),
        migrations.AddField(
            model_name='exam',
            name='subname',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='public.subjects'),
        ),
    ]
