# Generated by Django 5.0.1 on 2024-01-28 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam', '0004_exam_department_exam_semester_exam_subname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examname', models.TimeField(default='', max_length=500)),
                ('roomname', models.TimeField(default='', max_length=500)),
            ],
        ),
    ]
